name: Helm Chart Releaser
on:
  push:
    branches: [ "feature/post_helm_chart" ]
    tags: [ "helm-v*" ]
  pull_request:
    branches: [ "*" ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@v1
        with:
          version: 3.3.4
      - name: Linting Chart
        run: helm lint ./charts/kube-green
      - name: Setup Chart Linting
        id: lint
        uses: helm/chart-testing-action@v2.3.0
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ./.github/configs/ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - name: Run chart-testing (lint)
        run: ct lint --debug --charts charts/kube-green --config ./.github/configs/ct.yaml --lint-conf ./.github/configs/lintconf.yaml
      - name: Run docs-testing (helm-docs)
        id: helm-docs
        uses: actions/checkout@v3
        uses: gabe565/setup-helm-docs-action@v1
        run: |
          make helm-docs-ensure
          bin/helm-docs -d | diff charts/kube-green/README.md -
          if [ $? -ne 0 ]; then
            echo -e '\033[0;31mDocumentation outdated! (Run make helm-docs locally and commit)\033[0m ❌'
            diff charts/kube-green/README.md -
            exit 1
          else
            echo -e '\033[0;32mDocumentation up to date\033[0m ✔'
          fi
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@v1
        with:
          version: 3.3.4
      - name: Helm Chart Releaser
        # You may pin to the exact commit or the version.
        # uses: helm/chart-releaser-action@a917fd15b20e8b64b94d9158ad54cd6345335584
        uses: helm/chart-releaser-action@v1.6.0
        with:
          # The relative path to the chart-releaser config file
          charts_dir: charts
          install_dir: .

